server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: ${url:jdbc:mysql://192.168.99.100:3306/sakila}
    username: ${username:root}
    password: ${password:admin}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hand.javatest5.domain.entity
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers: com.hand.javatest5.infra.tkMapper.TkMapper
  identity: MYSQL


